name: Docker Image Publish

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker build . --tag ghcr.io/sheodox/alexandrite:${{ github.event.release.tag_name }} --tag ghcr.io/sheodox/alexandrite:latest
          docker push ghcr.io/sheodox/alexandrite:${{ github.event.release.tag_name }}
          docker push ghcr.io/sheodox/alexandrite:latest
